# Stage 1: Build stage
FROM golang:1.22.0-alpine AS build

# Set the working directory
WORKDIR /app

# Copy and download dependencies
COPY main.go .
COPY go.mod .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-s -w' -o myapp .

# Stage 2: Final stage
FROM scratch

# # # Set the working directory
WORKDIR /app

# # # Copy the binary from the build stage
COPY --from=build /app/myapp .

# Set the entrypoint command
ENTRYPOINT ["/app/myapp"]